### ISSUE TITLE
サイドメニューのタイトル押したときのイベントいらなくね？

### ISSUE THREAD

**Issue by kotaro3** [Gen-Arch/fuck_fish_front#2]
閲覧とかすぐに見たいページへ移動するのにいちいちタイトル押さないと項目が出てこないから少しストレスを感じるのでデフォルトで表示させてほしい

**Comment by gen-arch** [comment]
しぐれちゃん渾身のかっこいいふぁなので却下

**Comment by kotaro3** [comment]
どこがかっこいいのかを教えてほしい。特に無いなら使いづらいので直したいんだよなぁ

**Comment by kotaro3** [comment]
デフォ表示で妥協する

**Comment by gen-arch** [comment]
常時表示だとある意味なくね？

**Comment by gen-arch** [comment]
てｓｔ

**Comment by kotaro3** [comment]
そもそも隠す事自体意味ある？
今の所隠すほど項目数無いし個人的にはただのおしゃれ機能にしか見えないからいらない気がするけど

**Comment by gen-arch** [comment]
おっしゃるとおり、意味のないおしゃれ機能だからな

**Comment by Raimu0474** [comment]
にゅるっと動かしていえーいって言ってたやつだからね
